### ISSUE TITLE
dds files for texture

### ISSUE THREAD

**Issue by blazespinnaker** [ClemensX/ShadedPath12#1]
I think the dds files didn't get committed, eg grassdirt8.dds .. can you add them as well?

Cheers

**Comment by ClemensX** [comment]
I don't want to pollute the GitHub repository with these large media files. But I will look for an alternative download possibility. Also, I can only do this for the texture files I own or that are publicly available.

**Comment by ClemensX** [comment]
Made a release version. That allowed me to upload a large binary file. All textures of the example apps are included. Please acknowledge the license for the media files! Basically you can only use them for local test and not redistribute them.
